services:
  db:
    image: postgis/postgis:13-master
    container_name: idrofobia_db
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123