services:
  database:
    container_name: idrofobia_db
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123

  bot:
    build:
      context: .
    volumes:
      - ./config/production.json:/app/config/production.json

  cache:
    ports:
      - 6379:6379
    container_name: idrofobia_cache
    volumes:
      - ./docker/volumes/cache/data:/data