services:
  database:
    image: postgis/postgis:13-master

  bot:
    build:
      dockerfile: docker/dockerfiles/bot/Dockerfile
    depends_on:
      - database
      - bot_cache
  
  bot_cache:
    image: redis:7
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']